# permissions to do viewer packages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: package-viewer-role
rules:
- apiGroups:
  - go.mbell.dev
  resources:
  - packages
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - go.mbell.dev
  resources:
  - packages/status
  verbs:
  - get
